force-app/main/default/objects/Contact/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Junior</fullName>
            </value>
            <value>
                <fullName>Middle</fullName>
            </value>
            <value>
                <fullName>Senior</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interview_Answer__c/Interview_Answer__c.object-meta.xml
<CustomObject>
    <label>Interview Answer</label>
    <nameField>
        <displayFormat>IA-{0000}</displayFormat>
        <label>Interview Answer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interview Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Interview_Answer__c/fields/Grade__c.field-meta.xml
<CustomField>
    <fullName>Grade__c</fullName>
    <label>Grade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not evaluated</fullName>
            </value>
            <value>
                <fullName>None – 0</fullName>
            </value>
            <value>
                <fullName>Beginner - 1</fullName>
            </value>
            <value>
                <fullName>Good - 2</fullName>
            </value>
            <value>
                <fullName>Strong - 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interview_Answer__c/fields/Interview_Summary__c.field-meta.xml
<CustomField>
    <fullName>Interview_Summary__c</fullName>
    <label>Interview Summary</label>
    <referenceTo>Interview_Summary__c</referenceTo>
    <relationshipLabel>Interview Answers</relationshipLabel>
    <relationshipName>Interview_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Interview_Answer__c/fields/Topic__c.field-meta.xml
<CustomField>
    <fullName>Topic__c</fullName>
    <label>Topic</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Interview_Summary__c/Interview_Summary__c.object-meta.xml
<CustomObject>
    <label>Interview Summary</label>
    <nameField>
        <displayFormat>IS-{0000}</displayFormat>
        <label>Interview Summary Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interview Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Interview_Summary__c/fields/Gaps__c.field-meta.xml
<CustomField>
    <fullName>Gaps__c</fullName>
    <label>Gaps</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Interview_Summary__c/fields/High_Potential__c.field-meta.xml
<CustomField>
    <fullName>High_Potential__c</fullName>
    <label>High Potential</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low potential</fullName>
            </value>
            <value>
                <fullName>Regular</fullName>
            </value>
            <value>
                <fullName>High Potential</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interview_Summary__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trainee</fullName>
            </value>
            <value>
                <fullName>Junior low</fullName>
            </value>
            <value>
                <fullName>Junior</fullName>
            </value>
            <value>
                <fullName>Junior strong</fullName>
            </value>
            <value>
                <fullName>Intermediate low</fullName>
            </value>
            <value>
                <fullName>Intermediate</fullName>
            </value>
            <value>
                <fullName>Intermediate strong</fullName>
            </value>
            <value>
                <fullName>Senior low</fullName>
            </value>
            <value>
                <fullName>Senior</fullName>
            </value>
            <value>
                <fullName>Senior strong</fullName>
            </value>
            <value>
                <fullName>Leader low</fullName>
            </value>
            <value>
                <fullName>Leader</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interview_Summary__c/fields/Potentially_Hire__c.field-meta.xml
<CustomField>
    <fullName>Potentially_Hire__c</fullName>
    <label>Potentially Hire</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hire</fullName>
            </value>
            <value>
                <fullName>Not hire</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interview_Summary__c/fields/Summary_of_Qualification__c.field-meta.xml
<CustomField>
    <fullName>Summary_of_Qualification__c</fullName>
    <label>Summary of Qualification</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Interview_Summary__c/fields/Technical_English__c.field-meta.xml
<CustomField>
    <fullName>Technical_English__c</fullName>
    <label>Technical English</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Elementary</fullName>
            </value>
            <value>
                <fullName>Pre-intermediate</fullName>
            </value>
            <value>
                <fullName>Intermediate</fullName>
            </value>
            <value>
                <fullName>Upper-intermediate</fullName>
            </value>
            <value>
                <fullName>Advanced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interview_Summary__c/fields/Years_of_Experience__c.field-meta.xml
<CustomField>
    <fullName>Years_of_Experience__c</fullName>
    <label>Years of Experience</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/InterviewSummaryTests.cls
@isTest
public with sharing class InterviewSummaryTests {
    @TestSetup
    static void makeData(){
        Contact c = TestUtils.populateContact(false);
        Interview_Summary__c summary = TestUtils.populateInterviewSummary(c);
        TestUtils.populateInterviewTopics();
        TestUtils.populateInterviewAnswer(summary);
    }

    @isTest
    static void testAddInfo() {
        ContentVersion cv = TestUtils.createTestExcel();
        ContentDocument cd = [SELECT Id FROM ContentDocument WHERE LatestPublishedVersionId =: cv.Id];
        Interview_Summary__c summary = [
            SELECT Summary_of_Qualification__c, Years_of_Experience__c, Level__c,
            Gaps__c, Technical_English__c, High_Potential__c, Potentially_Hire__c,
            (SELECT Grade__c, Topic__c FROM Interview_Answers__r)
            FROM Interview_Summary__c
        ];

        Test.startTest();
        InterviewSummaryController.addInfo(summary.Id, cd.Id);
        Test.stopTest();

        Integer expectedResult = 2;
        Integer actualResult = [SELECT Count() FROM ContentVersion WHERE ContentDocumentId =: cd.Id];
        System.assert(expectedResult == actualResult);
    }

    @isTest
    static void testCheckJobStatusCompleted() {
        ContentVersion cv = TestUtils.createTestExcel();
        ContentDocument cd = [SELECT Id FROM ContentDocument WHERE LatestPublishedVersionId =: cv.Id];
        Interview_Summary__c summary = [
            SELECT Summary_of_Qualification__c, Years_of_Experience__c, Level__c,
            Gaps__c, Technical_English__c, High_Potential__c, Potentially_Hire__c,
            (SELECT Grade__c, Topic__c FROM Interview_Answers__r)
            FROM Interview_Summary__c
        ];
        
        Test.startTest();
        Id jobId = InterviewSummaryController.addInfo(summary.Id, cd.Id);
        Test.stopTest();

        String jobStatus = InterviewSummaryController.checkJobStatus(jobId)[0];
        System.assert(jobStatus == 'Completed', 'expected Completed, got ' + jobStatus);
    }

    @isTest
    static void testDeleteUploadedDocScheduled() {
        ContentDocument doc = TestUtils.createTestDoc();

        Test.startTest();
        InterviewSummaryController.deleteUploadedDocScheduled(doc.Id, doc.Title);
        Test.stopTest();

        Integer documentsCount = [SELECT Count() FROM ContentDocument];
        System.assert(documentsCount == 0);
    }

    @isTest
    static void testDeleteUploadedDoc() {
        ContentDocument doc = TestUtils.createTestDoc();

        Test.startTest();
        InterviewSummaryController.deleteUploadedDoc(doc.Id);
        Test.stopTest();

        Integer documentsCount = [SELECT Count() FROM ContentDocument];
        System.assert(documentsCount == 0);
    }
}